paises = [
  { pais: "Alaska", indicativo: 1907 },
  { pais: "Albania", indicativo: 355 },
  { pais: "Alemania", indicativo: 49 },
  { pais: "Andorra", indicativo: 376 },
  { pais: "Angola", indicativo: 244 },
  { pais: "Arabia Saudí", indicativo: 966 },
  { pais: "Argelia", indicativo: 213 },
  { pais: "Argentina", indicativo: 54 },
  { pais: "Armenia", indicativo: 374 },
  { pais: "Australia", indicativo: 61 },
  { pais: "Austria", indicativo: 43 },
  { pais: "Bahreim", indicativo: 973 },
  { pais: "Bangladesh", indicativo: 880 },
  { pais: "Bélgica", indicativo: 32 },
  { pais: "Bolivia", indicativo: 591 },
  { pais: "Bosnia", indicativo: 387 },
  { pais: "Brasil", indicativo: 55 },
  { pais: "Bulgaria", indicativo: 359 },
  { pais: "Cabo Verde", indicativo: 238 },
  { pais: "Camboya", indicativo: 855 },
  { pais: "Camerún", indicativo: 237 },
  { pais: "Canadá", indicativo: 1 },
  { pais: "Centroafricana, Rep.", indicativo: 236 },
  { pais: "Checa, Rep.", indicativo: 420 },
  { pais: "Chile", indicativo: 56 },
  { pais: "China", indicativo: 86 },
  { pais: "Chipre", indicativo: 357 },
  { pais: "Colombia", indicativo: 57 },
  { pais: "Congo, Rep. del", indicativo: 242 },
  { pais: "Congo, Rep. Democ.", indicativo: 243 },
  { pais: "Corea, Rep. Democ.", indicativo: 850 },
  { pais: "Corea, Rep.", indicativo: 82 },
  { pais: "Costa de Marfil", indicativo: 225 },
  { pais: "Costa Rica", indicativo: 506 },
  { pais: "Croacia", indicativo: 385 },
  { pais: "Cuba", indicativo: 53 },
  { pais: "Dinamarca", indicativo: 45 },
  { pais: "Dominicana, Rep.", indicativo: 1809 },
  { pais: "Ecuador", indicativo: 593 },
  { pais: "Egipto", indicativo: 20 },
  { pais: "El Salvador", indicativo: 503 },
  { pais: "Emiratos Árabes Unidos", indicativo: 971 },
  { pais: "Eslovaca, Rep.", indicativo: 421 },
  { pais: "Eslovenia", indicativo: 386 },
  { pais: "España", indicativo: 34 },
  { pais: "Estados Unidos", indicativo: 1 },
  { pais: "Estonia", indicativo: 372 },
  { pais: "Etiopía", indicativo: 251 },
  { pais: "Filipinas", indicativo: 63 },
  { pais: "Finlandia", indicativo: 358 },
  { pais: "Francia", indicativo: 33 },
  { pais: "Gibraltar", indicativo: 9567 },
  { pais: "Grecia", indicativo: 30 },
  { pais: "Groenlandia", indicativo: 299 },
  { pais: "Guatemala", indicativo: 502 },
  { pais: "Guinea Ecuatorial", indicativo: 240 },
  { pais: "Haití", indicativo: 509 },
  { pais: "Hawai", indicativo: 1808 },
  { pais: "Honduras", indicativo: 504 },
  { pais: "Hong Kong", indicativo: 852 },
  { pais: "Hungría", indicativo: 36 },
  { pais: "India", indicativo: 91 },
  { pais: "Indonesia", indicativo: 62 },
  { pais: "Irán", indicativo: 98 },
  { pais: "Irak", indicativo: 964 },
  { pais: "Irlanda", indicativo: 353 },
  { pais: "Islandia", indicativo: 354 },
  { pais: "Israel", indicativo: 972 },
  { pais: "Italia", indicativo: 39 },
  { pais: "Jamaica", indicativo: 1876 },
  { pais: "Japón", indicativo: 81 },
  { pais: "Jordania", indicativo: 962 },
  { pais: "Kenia", indicativo: 254 },
  { pais: "Kuwait", indicativo: 965 },
  { pais: "Laos", indicativo: 856 },
  { pais: "Letonia", indicativo: 371 },
  { pais: "Líbano", indicativo: 961 },
  { pais: "Liberia", indicativo: 231 },
  { pais: "Libia", indicativo: 218 },
  { pais: "Liechtenstein", indicativo: 41 },
  { pais: "Lituania", indicativo: 370 },
  { pais: "Luxemburgo", indicativo: 352 },
  { pais: "Madagascar", indicativo: 261 },
  { pais: "Malasia", indicativo: 60 },
  { pais: "Malta", indicativo: 356 },
  { pais: "Marruecos", indicativo: 212 },
  { pais: "Martinica", indicativo: 596 },
  { pais: "Mauritania", indicativo: 222 },
  { pais: "México", indicativo: 52 },
  { pais: "Moldavia", indicativo: 373 },
  { pais: "Mónaco", indicativo: 377 },
  { pais: "Mongolia", indicativo: 976 },
  { pais: "Mozambique", indicativo: 258 },
  { pais: "Namibia", indicativo: 264 },
  { pais: "Nepal", indicativo: 977 },
  { pais: "Nicaragua", indicativo: 505 },
  { pais: "Nigeria", indicativo: 234 },
  { pais: "Noruega", indicativo: 47 },
  { pais: "Nueva Zelanda", indicativo: 64 },
  { pais: "Países Bajos", indicativo: 31 },
  { pais: "Pakistán", indicativo: 92 },
  { pais: "Panamá", indicativo: 507 },
  { pais: "Paraguay", indicativo: 595 },
  { pais: "Perú", indicativo: 51 },
  { pais: "Polonia", indicativo: 48 },
  { pais: "Portugal", indicativo: 351 },
  { pais: "Puerto Rico", indicativo: 1787 },
  { pais: "Qatar", indicativo: 974 },
  { pais: "Reino Unido", indicativo: 44 },
  { pais: "Rumania", indicativo: 40 },
  { pais: "Rusia", indicativo: 7 },
  { pais: "San Marino", indicativo: 378 },
  { pais: "Senegal", indicativo: 221 },
  { pais: "Singapur", indicativo: 65 },
  { pais: "Siria", indicativo: 963 },
  { pais: "Somalia", indicativo: 252 },
  { pais: "Sri-Lanka", indicativo: 94 },
  { pais: "Sudáfrica", indicativo: 27 },
  { pais: "Sudán", indicativo: 249 },
  { pais: "Suecia", indicativo: 46 },
  { pais: "Suiza", indicativo: 41 },
  { pais: "Tailandia", indicativo: 66 },
  { pais: "Taiwan", indicativo: 886 },
  { pais: "Tanzania", indicativo: 255 },
  { pais: "Túnez", indicativo: 216 },
  { pais: "Turquía", indicativo: 90 },
  { pais: "Ucrania", indicativo: 380 },
  { pais: "Uganda", indicativo: 256 },
  { pais: "Uruguay", indicativo: 598 },
  { pais: "Vaticano", indicativo: 39 },
  { pais: "Venezuela", indicativo: 58 },
  { pais: "Vietnam", indicativo: 84 },
  { pais: "Yemen", indicativo: 967 },
  { pais: "Yugoslavia", indicativo: 381 },
  { pais: "Zambia", indicativo: 260 },
  { pais: "Zimbawe", indicativo: 263 }
];
